#!/usr/bin/env perl
use warnings;
use strict;
use Getopt::Long;
use FindBin qw($Bin);
use lib "$Bin/../lib";
use Cwd;

## This program is Copyright (C) 2018-19, Felix Krueger (felix.krueger@babraham.ac.uk)

## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.

## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.

## You should have received a copy of the GNU General Public License
## along with this program. If not, see <http://www.gnu.org/licenses/>.


### This script filters the latest VCF file for various SNPs versus the GRCm38 mouse genome build and writes high confidence SNPs into a folder called 'SNPs_Sanger';
### It has been tested with the latest version of the SNP file 'mgp.v5.merged.snps_all.dbSNP142.vcf.gz' at the time of writing (11 May 2016). I can't guarantee that
### it will work with any other supplied VCF file. A new version of the SNP file is supposed to be released in the first half of 2019

## Reading in a BAM or SAM file
my $pipeline_version = '0.1.0';
my $parent_dir = getcwd();
my %strains;
my ($vcf_file,$genome_folder,$nmasking,$genome_build) = process_commandline ();

my %snps; # storing all filtered SNPs

warn "\nSummarising reStraining - Genome Preparation - Parameters\n";
warn "="x50,"\n";

warn "Processing SNPs from VCF file:\t\t$vcf_file\n";
warn "Reference genome:\t\t\t$genome_folder\n";
warn "\n";

### Strain information
print "Generating N-masking output for all of the following strains:\n";
print "="x37,"\n";  
foreach my $ind(sort {$a<=>$b} keys %strains){
      print "$strains{$ind}->{strain} :|: ";
}
print "\n";
print "="x37,"\n\n";

sleep(1);

### Dealing with chromosomes - At the moment we are trying to limit the analysis on chromosome 1 [mainly for time and memory reasons]

my @chroms = (1); 
# @chroms = detect_chroms(); # this alternate method will detect all chromosomes from the VCF header and use those instead.

print "Using the following chromosome(s) [currently hardcoded]:\t";
# print "Using the following chromosomes (detected from VCF file >>$vcf_file<<):\n";
print join ("\t",@chroms),"\n\n";


### Storing the entire genome sequence
my %chromosomes; # genomic sequence
read_genome_into_memory($parent_dir);

### Determining and Filtering homozygous high-confidence SNPs for the strain in question
my $all_SNPs = filter_relevant_SNP_calls_from_VCF(); # the last number is the strain identity, here the first strain
warn "Finished filtering and writing out SNPs\n\n";

### Create modified genome
my $new_n_total = 0;
my $new_snp_total = 0;
my $already_total = 0;
my $low_confidence = 0;

# Writing a genome generation report file
my $report = "reStrainingOrder_genome_preparation_report.txt";
open (REPORT,'>',$report) or die "Failed to write to file $report: $!\n";

for my $chr (@chroms) {
    create_modified_chromosome($chr);
}

if ($nmasking){
    warn "\n\nSummary\n$new_n_total Ns were newly introduced into the N-masked genome for all current MGP strains in total\n";
    print REPORT "\nSummary\n$new_n_total Ns were newly introduced into the N-masked genome for all current MGP strains in total\n";
}
warn "\n";
close REPORT;

warn "All done. Genome(s) are now ready to be indexed with your favourite aligner!\nFYI, aligners known to work with reStrainingOrder are Bowtie2, Tophat, STAR, HISAT2, HiCUP and Bismark (STAR and HISAT2 require disabling soft-clipping, please check the manual for details)\n\n";      



#############################################################
### SUBROUTINES
#############################################################


sub create_modified_chromosome {
    
    my ($chr) = @_; # $strain may be strain 1 or 2
    warn "Processing chromosome $chr\n";
    
    unless ($chromosomes{$chr}){
	   warn "\nThe chromosome name given in the VCF file was '$chr' and was not found in the reference genome.\nA rather common mistake might be that the VCF file was downloaded from Ensembl (who use chromosome names such as 1, 2, X, MT)\nbut the genome from UCSC (who use chromosome names such as chr1, chr2, chrX, chrM)\n";
        warn "The chromosome names in the reference genome folder were:\n";
    	foreach my $c (sort keys %chromosomes){
    	    warn "$c\n";
    	}
	   die "[FATAL ERROR] Please ensure that the same version of the genome is used for both VCF annotations and reference genome (FastA files). Exiting...\n\n";
    }

    my $n_sequence = $chromosomes{$chr};

    warn "Getting SNPs for chromosome $chr...\n";
    my @snps = @{read_snps($chr)};
    warn "done.\n";
    
    unless (@snps){
	   @snps = ();
	   warn "Clearing SNP array...\n"
    }
    
    my $count = 0;

    my $lastPos = 0;

    my $already = 0;
    my $warn = 0;
    my $new_n = 0;
    my $new_snp = 0;

    foreach my $snp (@snps) {
    	# Apply the SNP
    	++$count;
    	# warn "$snp->[0]\t$snp->[1]/$snp->[2]\n";
    	if ($snp->[0] == $lastPos) {
    	    # Duplicate SNP
    	    next;
    	}
          
    	$lastPos = $snp->[0];
    	
    	# Check if the reference base is the same as the SNP base
    	#if (substr ($sequence,$snp->[0]-1,1) eq $snp->[2]) {
    	    # warn "Skipping $snp->[0] $snp->[1]/$snp->[2] since the ref and SNP base are the same\n";
    	 #   ++$already;
    	 #   next;
    	#}
          
    	# Check the reference base is correct
    	if (substr ($n_sequence,$snp->[0]-1,1) ne $snp->[1]) {
    	    warn "Skipping $snp->[0] $snp->[1]/$snp->[2] since the reference base didn't match\n";
    	    $warn++;
    	    next;
    	}
          
    	### Ref/Alt bases are matching, so we can proceed to changing the ref base for the SNP base or Ns (N-masking)
    	
    	### N-masking 
    	if ($nmasking){ # default
    	    my $return =  substr($n_sequence,($snp->[0])-1,1,'N');  # Replacing the base with 'N'
    	    unless ($return){
    		  warn "Replacing failed...\n";
    	    }
    	    ++$new_n;
    	}
	
    }
  
    $new_n_total += $new_n;
    $new_snp_total += $new_snp;
     
    $already_total += $already;
    if ($nmasking){ 
	   write_SNP_chromosome($chr,$n_sequence,1);
    }
    
    warn "$count SNPs total for chromosome $chr\n";
    if ($nmasking){ # default
	   warn "$new_n positions on chromosome $chr were changed to 'N'\n";
	   print REPORT "$new_n positions on chromosome $chr were changed to 'N'\n";
    }
    warn "\n";

}


sub write_SNP_chromosome {

    my ($chr,$sequence,$nm) = @_; # $nm will discriminate between N-masking and full sequence output
    if ($nm){
	   warn "Writing modified chromosome (N-masking)\n";
    }
    else{
	   die "Not N-masking is not an option!\n";
    }
    
    my $type;
    my $outfile;
    
    if ($nm){
	   $type = 'N-masked';
	   $outfile = "chr${chr}.N-masked.fa";
    }
    
    # warn "Starting sequence is ".length($sequence)." bp\n";
    if ($nm){
	    warn "Writing N-masked output to: ${parent_dir}/unique_MGP_strains_${type}/$outfile\n";
	    unless (-d "${parent_dir}/unique_MGP_strains_${type}/"){ # creating the output directory if required
	       mkdir "${parent_dir}/unique_MGP_strains_${type}/";
	    }      
    	open (OUT,'>',"${parent_dir}/unique_MGP_strains_${type}/${outfile}") or die "Failed to write to file ${parent_dir}/unique_MGP_strains_${type}/${outfile}: $!\n\n";
    	print OUT ">$chr\n";
    }
    
    my $pos = 0;

    # Writing out chromosome files with 100 characters per line
    while ($pos < length($sequence)-100) {
	   print OUT substr($sequence,$pos,100),"\n";
	   $pos += 100;
    }
    print OUT substr($sequence,$pos),"\n"; # rest
    close OUT or die $!;
   
}


sub read_snps {
    
    my ($chr) = @_;
    my @snps = ();
    my $file = "${parent_dir}/SNPs_directory/chr$chr.txt";

    ### If the SNP folder doesn't exist we can be certain that something is going wrong
    unless (-d "${parent_dir}/SNPs_directory"){
	   die "Folder >>${parent_dir}/SNPs_directory<< did not exist, I'm afraid something seems to have gone wrong...\n\n";
    }

    ### not sure but I think for some chromosomes there might not be any SNP files, e.g. chr MT or chrY. In this case the sequence is written out again unmodified
    unless (-e $file) {
	   warn "Couldn't find SNP file for chromosome '$chr' '$file' didn't exist. Skipping...\n";
	   return \@snps;
    }
    warn "Reading SNPs from file $file\n";
    
    open (IN,$file) or die $!;
    $_ = <IN>; # chromosome name header line
    while (<IN>) {
	   $_ =~ s/\r//; # Windows line endings...
	   chomp;
	   # warn "$_\n"; sleep(1);
	   next unless ($_);
	
	   my (undef,undef,$pos,$strand,$allele) = split(/\t/);
	   # warn "$pos , $strand , $allele\n"; sleep(1);
	   next unless ($allele);
	
	   my ($ref_allele,$snp_allele);

    	if ($allele =~ /^([GATC])\/([GATC])$/) {
    	    $ref_allele = $1;
    	    $snp_allele = $2;
    	}
    	else {
    	    warn "Skipping allele '$allele' as it appears to contain non DNA bases (only G,A,T,C allowed)\n";
    	    next;
    	}
	
    	if ($strand == -1) { # if the strand is given as -1 it means that the SNP is on the reverse strand and thus needs reverse-coplementing
    	    $ref_allele =~ tr/GATC/CTAG/;
    	    $snp_allele =~ tr/GATC/CTAG/;
    	}
	
    	# warn  "$pos , $ref_allele , $snp_allele\n"; sleep(1);
    	push @snps,[$pos,$ref_allele,$snp_allele];
    }

    # sorting snps
    @snps = sort {$a->[0] <=> $b->[0]} @snps;

    return \@snps;
    
    close IN or warn "Failed to close filehandle IN for file $file: $!\n\n";

}

###

sub filter_relevant_SNP_calls_from_VCF{
    
    my ($strain, $strain_index, $strain_identity) = @_;    
    warn "Now reading from VCF file $vcf_file\n";

    if ($vcf_file =~ /gz$/){
	   open (IN,"gunzip -c $vcf_file |") or die "Failed to open file '$vcf_file': $!\n";
    } 
    else{
	   open (IN, $vcf_file) or die "Failed to read Input VCF file '$vcf_file': $!\n";
    }
    
    my %all_SNPs; # storing filtered SNPs
    my $count = 0;

    my $other = 0;
    my $too_many = 0;
    
    my %fhs;
    my $hcg_count = 0;
    my $low_confidence = 0;
    my $same = 0;
    my $homozygous = 0;
  
  
    my $dir = "SNPs_directory";
    unless (-d $dir){
		warn "Folder '$dir' doesn't exist. Creating it for you...\n\n";
		mkdir $dir or die "Failed to created directory $dir\n: $!\n\n";
	}
    
    # Opening filehandles for the SNP files
    for my $chr (@chroms) {
    	my $filename = "SNPs_directory/chr".$chr.'.txt';
    	open (my $fh,'>',$filename) or die "Couldn't open filehandle $!\n";
    	$fhs{$chr} = $fh;
        print {$fhs{$chr}} ">$chr\n";
    }  

    while (<IN>){
    	$_ =~ s/(\r|\n)//g; # removing end of line characters

        # warn "$_\n"; sleep(1);
    	next if ($_ =~ /^\#\#/); # filters out header information lines
    	# warn "$_\n"; sleep(1);
        if ($_ =~ /^\#CHROM/){ # Table Header
    	    #my ($name) = (split /\t/)[$strain_index];
    	    #warn "Analysing SNP fields for name >$name<\n";
    	    next;	
    	}
    	$count++;
    	if ($count%1000000 ==0){
    	    warn "processed $count lines\n";
    	}
		last if ($count == 10000);
    	# sleep(1);
        # foreach my $index(0..$#strains){
           # next if ($index <= 8); 
           # $strains{$strains[$index]} = $index; 
            # warn "$index\t$strains[$index]\n";
        #   }
        # }
        
    	# my ($chr,$pos,$ref,$alt,@strains) = (split /\t/)[0,1,3,4,];

        my ($chr,$pos,undef,$ref,$alt,undef,undef,undef,@strains) = (split /\t/);

        # warn "$chr , $pos , $ref , $alt\n"; sleep(1);
        unless ($chr eq '1'){
            warn "Reached a new chromosome ($chr), but we are currently limiting filtering to chromosome 1\n";
            last;
        }
        my $location = join (':',$chr,$pos);
        # warn "$location\n";   

        # Looping through all of the strains to find positions that are unique to one strain or another
        my $unique_snp;
        my $unique_strain;
        my $unique_index;
        my $pos_fails = 0;

        # The first 8 fields are irrelevant: #CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  
        foreach my $index (9..$#strains){
        	# print "$index\t$strains{$index}\t$strains[$index]\n"; sleep(1);

            # $strain is in the form: GT:GQ:DP:MQ0F:GP:PL:AN:MQ:DV:DP4:SP:SGB:PV4:FI
            my ($gt,$gq,$dp,$mq0f,$gp,$pl,$an,$mq,$dv,$dp4,$sp,$sgb,$pv4,$fi) = split/:/,$strains[$index];
        	   
            # warn "genotype: $gt\nfilter:   $fi\n";
        	# warn "$fi\n"; sleep(1);
        	# $gt is the Genotype:
        	# print "CHR: $chr\tPOS: $pos\tREF: $ref\tALT: $alt\tGT: $gt\tFILTER: $fi\t$strains{$index}\t$strains[$index]\n"; # sleep(1);
        	# '.'   = no genotype call was made
        	# '0/0' = genotype is the same as the reference genome
        	# '1/1' = homozygous alternative allele; can also be '2/2',
        	# '3/3', etc. if more than one alternative allele is present.
        	# '0/1' = heterozygous genotype; can also be '1/2', '0/2', etc.
        	
        	# $fi is FILTER, 1 for high confidence SNP, or 0 for low confidence
        	
        	### We are only looking for 1/1, 2/2 or 3/3 calls, and filter for high confidence as well
        	
           
            # Looking at the Filter tag first
            # warn "$fi\n"; sleep(1);
            if ($fi eq 1){
                # +$hcg_count;
				# warn "FI was high confidence\n";
            }
            else{
                ++$low_confidence;
                # warn "FI was $fi\n";
                next;
            }
            
        	# skipping if the reference base is not well defined in Black6
        	if ($ref =~ /[^ATCG]/){ # reference base contained any non A, C, T, G characters or more than one base
        	    warn "ref was: $ref; skipping\n";
        	    last;
        	}
        	
        	# skipping if the SNP is not well defined in the strain of interest
        	if ($alt =~ /[^ATCG,]/){ # Alt base contained any non A, C, T, G characters or commas which separate several different variants
        	    # warn "SNP was: $alt; GT was $gt; FI was: $fi; skipping\n";
        	    ++$too_many;
        	    last;
        	}
        	
     
        	# Filtering for genotype. If the genotype is the same as the reference we will move on to the next position and/or strain
        	if ($gt eq '0/0'){
        	    ++$same;
        	    # warn "same as reference, next...\n";
        	    next;
        	}
        	elsif ($gt eq '1/1'){
        	    ++$homozygous;
        	    if ($alt =~ /[^ATCG]/){ 	 
            		# warn "homozygous alternative allele: >$alt<\n";
            		my ($new_alt) = (split (/,/,$alt))[0];
            		# warn "New ALT is $new_alt\n";
            		# warn "genotype: $gt\nfilter:   $fi\n\n"; sleep(1);
            		$alt = $new_alt;  
        	    }
        	}
        	elsif ($gt eq '2/2'){
        	    # warn "$gt\n";
        	    ++$homozygous;
        	    if ($alt =~ /[^ATCG]/){ 	 
            		# warn "homozygous alternative allele: >$alt<\n";
            		my ($new_alt) = (split (/,/,$alt))[1];
            		# warn "New ALT is $new_alt\n\n"; sleep(1);
            		$alt = $new_alt;    
        	    }
        	}
        	elsif ($gt eq '3/3'){
        	    # warn "$gt\n";
        	    ++$homozygous;
        	    if ($alt =~ /[^ATCG]/){
        		    # warn "homozygous alternative allele: >$alt<\n";
        		    my ($new_alt) = (split (/,/,$alt))[2];                                                                                                        
         		    # warn "New ALT is $new_alt\n\n"; sleep(1);                                                                             
        		    $alt = $new_alt;   
        	    }
        	}
        	else{
        	    # this could be positions without genotype call ./. or any form of heterozygous call. In any case we will blacklist these positions and not use them for dual genomes
        	    # we do skip these positions but keep them on the 'blacklist' for dual genomes
        	    ++$other;
        	    #  warn "$gt\n"; 
        	    next;
        	}

        	
        	# Output example
        	# Variation ID    Chromosome name Position on Chromosome (bp)     Strand  Allele
            # rs2020560       10      98212004        1       A/T
        	
            ### If we made it this far the SNP is a homozygous substitution in the current strain, and it was a high confidence call
            
            my $SNP = join ("\t",$strains{$index}->{strain},$chr,$pos,'1',join ("\/",$ref,$alt));
            # field 4: 1 means top strand, -1 means reverse strand
            # warn "$SNP\n";sleep(1);
            if (defined $unique_snp){
                # warn "SNP was already defined by a previous strain. Failing this position out...\n";
                $pos_fails++;
            }
            else{
                $unique_strain = $strain;
                $unique_snp = $SNP;
                $unique_index = $index;
                warn  "SNP was not present yet, storing it (for strain $strains{$index})\n";
            }

            #if (exists $snps{$location} ){
             #   warn "SNP $snps{$location} position was present already\n";
            #}
            #else{
             #   $snps{$location} = $SNP;
             #   warn  "High confidence SNP for strain $strains{$index}\n";
            #}
        	# print {$fhs{$chr}} join ("\t",$count,$chr,$pos,'1',join ("\/",$ref,$alt),$strain),"\n";
    	}

        if ($pos_fails){
            warn "Position was a SNP in several strains. Moving on to the next....\n"; sleep(1);
        }
        else{
            if (defined $unique_snp){
                warn "Position was unique!!!! >>> $unique_snp <<<\n\n";
                $snps{$location}->{snp} = $unique_snp;
                $snps{$location}->{strain} = $unique_strain;
                $strains{$unique_index}->{count}++;
            }  
        }
		sleep(1);
    }

    # Writing a report file
    my $report = "SNP_filtering_report.txt"; # $strain here may be strain 1 or strain 2
    open (REPORT,'>',$report) or die "Failed to write to file $report: $!\n";
    
    warn "\nSNP position summary for all MGP strains (based on mouse genome build $genome_build)\n";
    warn "="x77,"\n\n";
    warn "Positions read in total:\t$count\n\n";
    warn "$homozygous\tSNP were homozygous. Of these:\n";
    warn "$hcg_count\tSNP were homozygous and passed high confidence filters and were thus included into the all MGP strains genome\n";
    warn "\nNot included into MGP strains genome:\n";
    warn "$same\thad the same sequence as the reference\n";
    warn "$too_many\t\thad no clearly defined alternative base\n";
    warn "$other\t\tCalls were neither 0/0 (same as reference) or 1/1, 2/2, 3/3 (homozygous SNP)\n";
    warn "$low_confidence\t\twere homozygous but the filtering call was low confidence\n\n";

    print REPORT "SNP position summary for all MGP strains(based on mouse genome build $genome_build)\n";
    print REPORT "="x75,"\n\n";
    print REPORT "Positions read in total:\t$count\n\n";
    print REPORT "$homozygous\tSNP were homozygous. Of these:\n";
    print REPORT "$hcg_count\tSNP were homozygous and passed high confidence filters and were thus included into the all MGP strains genome\n";
    print REPORT "\nNot included into MGP strains genome:\n";
    print REPORT "$same\thad the same sequence as the reference\n";
    print REPORT "$too_many\t\thad no clearly defined alternative base\n";
    print REPORT "$other\t\tCalls were neither 0/0 (same as reference) or 1/1, 2/2, 3/3 (homozygous SNP)\n";
    print REPORT "$low_confidence\t\twere homozygous but the filtering call was low confidence\n\n";
    
    warn "UNIQUE SNP summary\n==================\n\n";
    warn "COUNT\tSTRAIN\n";
    print REPORT "UNIQUE SNP summary\n==================\n\n";
    print REPORT "COUNT\tSTRAIN\n";
    foreach my $index (sort {$a<=>$b} keys %strains){
        warn "$strains{$index}->{count}\t$strains{$index}->{strain}\n";
        print REPORT "$strains{$index}->{count}\t$strains{$index}->{strain}\n";
    }
    warn "\n\n";
    print REPORT "\n\n";

    # Also writing all SNP calls out to an all-SNP file
    my $all_SNPs = "all_unique_SNPs_MGP_${genome_build}.txt.gz";
    warn "Now printing a single list of all unique SNPs to >$all_SNPs<...\n";
    print REPORT "Printed a single list of all SNPs to >$all_SNPs<...\n";
    close REPORT or warn "Failed to close filehandle REPORT\n";

    if (-e $all_SNPs){
	   warn "File '$all_SNPs' existed in the folder already, overwriting it...\n\n";
    }
    open (ALLSNP,"| gzip -c - > $all_SNPs") or die "Failed to write to file $all_SNPs: $!\n";
    
    foreach my $location (keys %snps){
        my ($chr) = (split /\t/,$snps{$location}->{snp})[1];
        # wparn "CHR: $chr\n"; 
	    print ALLSNP "$snps{$location}->{snp}\n";
        print {$fhs{$chr}} "$snps{$location}->{snp}\n"; # also writing into the SNP folder
    }
    warn "complete\n\n";
    close ALLSNP;

}


sub detect_chroms{
    
    my %chrom; # detecting the chromosomes from the VCF file
    my @chrom;
    
    if ($vcf_file =~ /gz$/){
	open (DETECT,"gunzip -c $vcf_file |") or die "Failed to open file '$vcf_file': $!\n";
    }
    else{
	open (DETECT, $vcf_file) or die "Failed to read Input VCF file '$vcf_file': $!\n";
    }
    
    # warn "Detecting chromosomes from file '$vcf_file'\n\n";
    while (<DETECT>){
	$_ =~ s/(\r|\n)//g; # removing end of line characters
	last unless ($_ =~ /^\#/);
	
	if ($_ =~ /^\#\#contig/){ # filters header lines
	    # warn "$_\n"; # sleep(1);
	    $_ =~ /ID=(.+),/;
	    my $chr = $1;
	    # warn "Identified chromosome $chr\n";
	    unless (exists $chrom{$chr}){
		$chrom{$chr}++;
	    }
	}
    }
    
    foreach my $chr(keys %chrom){
	# warn "$chr\n";	
	push @chrom, $chr;
    }
    # close DETECT or warn "Failed to close filehandle DETECT: $!\n";
    return @chrom;
    
}

sub detect_strains{
    
    my $vcf_file = shift;
    my %strains; # detecting the available strains from the VCF file
    
    if ($vcf_file =~ /gz$/){
	open (STRAIN,"gunzip -c $vcf_file |") or die "Failed to open file '$vcf_file': $!\n";
    }
    else{
	open (STRAIN, $vcf_file) or die "Failed to read Input VCF file '$vcf_file': $!\n";
    }
    
    # warn "Detecting strains from file '$vcf_file'\n\n";
    while (<STRAIN>){
	$_ =~ s/(\r|\n)//g; # removing end of line characters
	next if ($_ =~ /^\#\#/);	
	if ($_ =~ /^\#CHROM/){ # header line listing all different strains
	    # warn "$_\n"; sleep(1);
	}
	last unless ($_ =~ /^\#/); # everything from now on are the SNPs themselves
	
	my @strains = split (/\t/);


	foreach my $index(0..$#strains){
	    next if ($index <= 8); # The first 8 fields are irrelevant: #CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  
	    $strains{$index}->{strain} = $strains[$index];
        $strains{$index}->{count} = 0;

	    # warn "$index\t$strains[$index]\n";
	   }
    }
    
    # close STRAIN or warn "Failed to close filehandle STRAIN: $!\n";
    return %strains;

}

sub read_genome_into_memory{
    
    ## working directoy
    my $cwd = shift;
    
    ## reading in and storing the specified genome in the %chromosomes hash
    chdir ($genome_folder) or die "Can't move to $genome_folder: $!";
    warn "Now reading in and storing sequence information of the genome specified in: $genome_folder\n\n";

    my @chromosome_filenames =  <*.fa>;

    ### if there aren't any genomic files with the extension .fa we will look for files with the extension .fasta
    unless (@chromosome_filenames){
      @chromosome_filenames =  <*.fasta>;
    }

    unless (@chromosome_filenames){
      die "The specified reference genome folder $genome_folder does not contain any sequence files in FastA format (with .fa or .fasta file extensions)\n";
    }

    my $SQ_count = 0;

    foreach my $chromosome_filename (@chromosome_filenames){

	open (CHR_IN,$chromosome_filename) or die "Failed to read from sequence file $chromosome_filename $!\n";
	### first line needs to be a fastA header
	my $first_line = <CHR_IN>;
	chomp $first_line;
	$first_line =~ s/\r//;
	### Extracting chromosome name from the FastA header
	my $chromosome_name = extract_chromosome_name($first_line);
	my $sequence;

	while (<CHR_IN>){
	  chomp;
	  $_ =~ s/\r//; # removing carriage returns if present
	  if ($_ =~ /^>/){
	
	    ### storing the previous chromosome in the %chromosomes hash, only relevant for Multi-Fasta-Files (MFA)
	    if (exists $chromosomes{$chromosome_name}){
	      print "chr $chromosome_name (",length $sequence ," bp)\n";
	      die "Exiting because chromosome name already exists. Please make sure all chromosomes have a unique name!\n";
	    }
	    else {
	      if (length($sequence) == 0){
		warn "Chromosome $chromosome_name in the multi-fasta file $chromosome_filename did not contain any sequence information!\n";
	      }
	      print "chr $chromosome_name (",length $sequence ," bp)\n";
	      $chromosomes{$chromosome_name} = $sequence;
	    }
	    ### resetting the sequence variable
	    $sequence = '';
	    ### setting new chromosome name
	    $chromosome_name = extract_chromosome_name($_);
	  }
	  else{
	    $sequence .= uc$_;
	  }
	}
	
 	### Processing last chromosome of a multi Fasta File or the only entry in case of single entry FastA files

	if (exists $chromosomes{$chromosome_name}){
	    print "chr $chromosome_name (",length $sequence ," bp)\t";
	    die "Exiting because chromosome name already exists. Please make sure all chromosomes have a unique name.\n";
	}
	else{
	    if (length($sequence) == 0){
		warn "Chromosome $chromosome_name in the file $chromosome_filename did not contain any sequence information!\n";
	    }

	    print "chr $chromosome_name (",length $sequence ," bp)\n";
	    $chromosomes{$chromosome_name} = $sequence;
	}
    }
    print "\n";
    chdir $cwd or die "Failed to move to directory $cwd\n";

}

sub extract_chromosome_name {
    ## Bowtie seems to extract the first string after the inition > in the FASTA file, so we are doing this as well
    my $fasta_header = shift;
    if ($fasta_header =~ s/^>//){
	my ($chromosome_name) = split (/\s+/,$fasta_header);
	return $chromosome_name;
    }
    else{
	die "The specified chromosome ($fasta_header) file doesn't seem to be in FASTA format as required!\n";
    }
}


###################################################################


sub process_commandline{
    my $help;
    my $version;
    my $vcf_file;
    my $list_strains;
    my $skip_filtering;
    my $genome_folder;
    my $nmasking;
    my $genome_build;
    
    my $command_line = GetOptions ('help|man'             => \$help,
				   'versions'             => \$version,
				   'list_strains'         => \$list_strains,
				   'vcf_file=s'           => \$vcf_file,
				   'nmasking'             => \$nmasking,
				   'reference_genome=s'   => \$genome_folder,
				   'genome_build=s'       => \$genome_build,
	);
  
    ### EXIT ON ERROR if there were errors with any of the supplied options
    unless ($command_line){
	die "Please respecify command line options\n";
    }
    
    ### HELPFILE
    if ($help){
	print_helpfile();
	exit;
    }
    
    if ($version){
	print << "VERSION";
	
                          reStrainingOrder - Genome Preparation
			           version: $pipeline_version
                             Copyright 2018-19, Felix Krueger
                                 Babraham Bioinformatics
                   https://github.com/FelixKrueger/reStrainingOrder

VERSION
		 ;
   	exit;
    }

    if (defined $vcf_file){
    	unless(-e $vcf_file){
    	    die "Input VCF file '$vcf_file' doesn't exist in the folder. Please check filenames and try again!\n\n";
    	}
    }
    else{
	   unless($skip_filtering){
	       die "\nYou need to provide a VCF file detailing SNPs positions with '--vcf_file your.file' (e.g.: --vcf mgp.v5.merged.snps_all.dbSNP142.vcf.gz). Please respecify!\n\n";
	   }
    }

    my $strain_index;
	%strains = detect_strains($vcf_file);

	if ($list_strains){
	    warn "\nAvailable genomes to choose from are:\n";
	    warn "="x37,"\n";
	    foreach my $strain(keys %strains){
	       print "$strain\n";
	    }
	    warn "="x37,"\n";
	    warn "\nPlease choose a strain using '--strain NAME' to continue.\n\n";
	    exit;
	}


    ### GENOME FOLDER
    
    unless ($genome_folder){
	   warn "Reference genome folder was not specified! Please use --reference_genome </genome/folder/>\n";
    	# print_helpfile();
    	exit;
    }
    my $parent_dir = getcwd();    

    ### checking that the genome folder exists  
    unless ($genome_folder =~/\/$/){
	   $genome_folder =~ s/$/\//;
    }
    
    if (chdir $genome_folder){
    	my $absolute_genome_folder = getcwd; ## making the genome folder path absolute
    	unless ($absolute_genome_folder =~/\/$/){
    	    $absolute_genome_folder =~ s/$/\//;
    	}
    	warn "Reference genome folder provided is $genome_folder\t(absolute path is '$absolute_genome_folder)'\n\n";
    	$genome_folder = $absolute_genome_folder;
    }
    else{
	   die "Failed to move to genome folder > $genome_folder <: $!\n\nSNPsplit_genome_preparation --help for more details\n\n";
    }
    chdir $parent_dir or die "Failed to move back to parent directory $parent_dir\n\n";

    ### N-masking mode of action
    $nmasking = 1; # This is the default
    
    unless (defined $genome_build){
    	$genome_build = 'GRCm38';
    }

    return ($vcf_file,$genome_folder,$nmasking,$genome_build);

}


sub print_helpfile{
  print <<EOF

  SYNOPSIS:

SNPsplit_genome_preparation is designed to read in a variant call files from the Mouse Genomes Project (e.g. this latest
file: 'mgp.v5.merged.snps_all.dbSNP142.vcf.gz') and generate new genome versions where the strain SNPs are either incorporated
into the new genome (full sequence) or masked by the ambiguity nucleo-base 'N' (N-masking).

SNPsplit_genome_preparation may be run in two different modes:

Single strain mode:

   1) The VCF file is read and filtered for high-confidence SNPs in the strain specified with --strain <name>
   2) The reference genome (given with --reference_genome <genome>) is read into memory, and the filtered high-
      confidence SNP positions are incorporated either as N-masking (default) or full sequence (option --full_sequence)

Dual strain mode:

   1) The VCF file is read and filtered for high-confidence SNPs in the strain specified with --strain <name>
   2) The reference genome (given with --reference_genome <genome>) is read into memory, and the filtered high-
      confidence SNP positions are incorporated as full sequence and optionally as N-masking
   3) The VCF file is read one more time and filtered for high-confidence SNPs in strain 2 specified with --strain2 <name>
   4) The filtered high-confidence SNP positions of strain 2 are incorporated as full sequence and optionally as N-masking
   5) The SNP information of strain and strain 2 relative to the reference genome build are compared, and a new Ref/SNP
      annotation is constructed whereby the new Ref/SNP information will be Strain/Strain2 (and no longer the standard
      reference genome strain Black6 (C57BL/6J))
   6) The full genome sequence given with --strain <name> is read into memory, and the high-confidence SNP positions between
      Strain and Strain2 are incorporated as full sequence and optionally as N-masking

The resulting .fa files are ready to be indexed with your favourite aligner. Proved and tested aligners include Bowtie2,
Tophat, STAR, Hisat2, HiCUP and Bismark. Please note that STAR and Hisat2 may require you to disable soft-clipping, please
refer to the SNPsplit manual for more details

Both the SNP filtering as well as the genome preparation write out little report files for record keeping.
Please note that the SNPsplit genome preparation writes out files and creates new folders for the SNPs and new genomes into
the current working directory, so move there before invoking SNPsplit_genome_preparation.


  USAGE:    SNPsplit_genome_preparation  [options] --vcf_file <file> --reference_genome /path/to/genome/ --strain <strain_name>


--vcf_file <file>             Mandatory file specifying SNP information for mouse strains from the Mouse Genomes Project
                              (http://www.sanger.ac.uk/science/data/mouse-genomes-project). The file used and approved is 
                              called 'mgp.v5.merged.snps_all.dbSNP142.vcf.gz'. Please note that future versions
                              of this file or entirely different VCF files might not work out-of-the-box but may require some
                              tweaking. SNP calls are read from the VCF files, and high confidence SNPs are written into
                              a folder in the current working directory called SNPs_<strain_name>/chr<chromosome>.txt,
                              in the following format:

                                          SNP-ID     Chromosome  Position    Strand   Ref/SNP
                              example:   33941939        9       68878541       1       T/G


--strain <strain_name>        The strain you would like to use as SNP (ALT) genome. Mandatory. For an overview of strain names
                              just run SNPsplit_genome_preparation selecting '--list_strains'.

--list_strains                Displays a list of strain names present in the VCF file for use with '--strain <strain_name>'.

--dual_hybrid                 Optional. The resulting genome will no longer relate to the original reference specified with '--reference_genome'.
                              Instead the new Reference (Ref) is defined by '--strain <strain_name>' and the new SNP genome
                              is defined by '--strain2 <strain_name>'. '--dual_hybrid' automatically sets '--full_sequence'.

                              This will invoke a multi-step process:
                                 1) Read/filter SNPs for first strain (specified with '--strain <strain_name>')
                                 2) Write full SNP incorporated (and optionally N-masked) genome sequence for first strain
                                 3) Read/filter SNPs for second strain (specified with '--strain2 <strain_name>')
                                 4) Write full SNP incorporated (and optionally N-masked) genome sequence for second strain
                                 5) Generate new Ref/Alt SNP annotations for Strain1/Strain2
                                 6) Set first strain as new reference genome and construct full SNP incorporated (and optionally 
                                    N-masked) genome sequences for Strain1/Strain2
                                                            

--strain2 <strain_name>       Optional for constructing dual hybrid genomes (see '--dual_hybrid' for more information). For an
                              overview of strain names just run SNPsplit_genome_preparation selecting '--list_strains'.

--reference_genome            The path to the reference genome, typically the strain 'Black6' (C57BL/6J), e.g.
                              '--reference_genome /bi/scratch/Genomes/Mouse/GRCm38/'. Expects one or more FastA files in this folder
                              (file extension: .fa or .fasta).

--skip_filtering              This option skips reading and filtering the VCF file. This assumes that a folder named
                              'SNPs_<Strain_Name>' exists in the working directory, and that text files with SNP information
                              are contained therein in the following format:

                                          SNP-ID     Chromosome  Position    Strand   Ref/SNP
                              example:   33941939        9       68878541       1       T/G

--nmasking                    Write out a genome version for the strain specified where Ref bases are replaced with 'N'. In the
                              Ref/SNP example T/G the N-masked genome would now carry an N instead of the T. The N-masked genome
                              is written to a folder called  '<strain_name>_N-masked/'. Default: ON.

--full_sequence               Write out a genome version for the strain specified where Ref bases are replaced with the SNP base.
                              In the Ref/SNP example T/G the full sequence genome would now carry a G instead of the T. The full
                              sequence genome is written out to folder called '<strain_name>_full_sequence/'. May be set in
                              addition to '--nmasking'. Default: OFF. 

--no_nmasking                 Disable N-masking if it is not desirable. Will automatically set '--full_sequence' instead.

--genome_build [name]         Name of the mouse genome build, e.g. GRCm38. Will be incorporated into some of the output files.
                              Defaults to 'GRCm38'.

--help                        Displays this help information and exits.

--version                     Displays version information and exits.


                                                             Last modified: 20 05 2019

EOF
    ;
  exit 1;
}

